### ISSUE TITLE
Training and testing data for the task

### ISSUE THREAD

**Issue by soumyasanyal** [msang/hateval#1]
Hi,
The competition webpage redirects to the link https://github.com/msang/hateval/tree/master/SemEval2019-Task5/datasets for datasets. But only trial data is available for download. Is the training and testing data publicly available at some other link?

**Comment by valeriobasile** [comment]
We are checking if we are allowed to directly share the data on github, perhaps password-protected. In the meantime you can try to write to the organizers, they will share the data privately.

**Comment by korymath** [comment]
Any follow up on this?

**Comment by valeriobasile** [comment]
We set up a form in order to release the data and being compliant with the GDPR. Please use that to request the dataset:
http://hatespeech.di.unito.it/hateval.html
